### ISSUE TITLE
Cool analytics

### ISSUE THREAD

**Issue by JarrettR** [vhs/nomos#1]
There is already graphing support. Should be possible to add things like: 

New users vs attrition

Day of week first signed up

etc

**Comment by JarrettR** [comment]
Number of unique door entries in the past, say, 3 months

**Comment by laftho** [comment]
Fancy new charts added!

https://github.com/vhs/nomos/pull/225

We can always add more but this adds:

- last months revenue vs this months (as expected revenue)
- new members in last 30 days
- total members (current month)
- total keyholders (current month)
- new keyholders in last 30 days
- last 18 months popular sign up heatmap of day of week vs hour of day
- last 3 months popular sign up heatmap of day of week vs hour of day
- last 18 months  popular sign up heatmap of day of week vs month
- last 18 months revenue breakdown
- last 18 months of change in membership
