### ISSUE TITLE
Admin "account pending" area

### ISSUE THREAD

**Issue by JarrettR** [vhs/nomos#102]
Accounts shouldn't be automatically added on new IPN, they should require some admin review.

A page for pending accounts would also allow cash members to self-report, solving issue #4

**Comment by laftho** [comment]
PR 119 adds an enhanced User List service which has a "Pending user" filter. Also as part of PR 114 IPN creates accounts but puts them in a pending state for admin review.

https://github.com/vhs/nomos/pull/119
https://github.com/vhs/nomos/pull/114
Marking this resolved.
