### ISSUE TITLE
Field for nickname in the user profile

### ISSUE THREAD

**Issue by garthomite** [vhs/nomos#148]
People like to use their handles, either on talk or slack.

When authentication takes place I would like to know what their handle is. For example if I do a report on who is using the laser, I would rather see just handles instead of real names. 

This information would also be good when I ask to authenticate a user by pin or service (such as slack).

Currently when I build an application that links to nomos I can authenticate the user but I don't have a great way to determine what their handle is.

**Comment by laftho** [comment]
basic identity info makes a lot of sense here.

Currently we have username.. that can be whatever the user wants (so long as it's distinct) but it is a login name..

At the very least it makes sense to return the UserID with these auth services. UserID then in turn can be used to query more details about the user but we should have identity stuff.

Adding 2 fields:

UserID
Username

@garthomite Does that suffice for what you are looking for for these features? Should we be adding a "display name" field to user profiles?

It's worth noting that by default & often a user's username is an email address.

**Comment by laftho** [comment]
RE https://github.com/vhs/nomos/blob/master/app/services/AuthService.php

**Comment by garthomite** [comment]
Username is perfect!

So yes if you can return UserID and Username on /services/web/AuthService1.svc/CheckService then I can use that when people authenticate.

```json
{
  "valid": true,
  "type": "key-holder",
  "privileges": [
      
  ]
}
```

becomes

```json
{
  "valid": true,
  "userId": 12345,
  "username": "garthomite",
  "type": "key-holder",
  "privileges": [
      
  ]
}
```

**Comment by laftho** [comment]
PR #159

Resolved.
