### ISSUE TITLE
Add user->valid property to User domain to determind active + mem_expire

### ISSUE THREAD

**Issue by laftho** [vhs/nomos#149]
In many places we want to ensure the user is an active paying member. Adding a domain property/method that checks user active + mem_expire would make for a simple way to ensure account validity.

Currently most door access auth services, etc don't necessarily check mem_expire to ensure that they are paying members.

Legacy MMP would often set the active filed on the user table via cron job or when the user attempted to login if mem_expire was less than now. Since we've removed legacy, checking a user's paid vailidity is both active + mem_expire.

**Comment by laftho** [comment]
new tool access implementation brings this to a higher priority. Bump.

**Comment by laftho** [comment]
foundational https://github.com/vhs/nomos/pull/236

**Comment by TyIsI** [comment]
#237 solved this, right?

**Comment by laftho** [comment]
@TyIsI indeed! woot ✨
