### ISSUE TITLE
Login page doesn't work in Safari

### ISSUE THREAD

**Issue by lukecyca** [vhs/nomos#226]
Steps to repro:

1. Go to https://membership.vanhack.ca with Safari  (I used 9.1.2)
2. Enter a valid email and password
3. Press return or click login

The form goes blank and this appears in the console:

<img width="1270" alt="screen shot 2016-12-06 at 8 14 19 am" src="https://cloud.githubusercontent.com/assets/366484/20933278/6dc7ba3a-bb8c-11e6-862c-5d8b0d59650e.png">

**Comment by laftho** [comment]
is this a really old version of safari? I would've thought it'd have a webkit version that supports ecma6..

**Comment by mikepkes** [comment]
Same version of safari, same problem.  This version of Safari came out this year and is the current in 10.11.6

**Comment by BruceFletcher** [comment]
I have no trouble with Nomos in Safari, but I think it might be a version issue.

ECMAScript 6 support: https://kangax.github.io/compat-table/es6/

Safari 10 is the only browser that is 100% ES6 compliant. This comes with "macOS Sierra 10.12" or whatever they're calling it this week.

On the other hand, Safari 9 is 54% compliant according to that chart. At a guess, Mac OS X 10.11 comes with Safari 9 and is not upgradable to Safari 10.

**Comment by lukecyca** [comment]
I just upgraded to Safari 10 with Mac OS X 10.10.5, so it is available even without upgrading to a new major version of Mac OS X.

Rather than "fixing" this issue, I think a better solution would be to enforce minimum browser requirements for Nomos, and show a warning if they are not met. Since we're a hackspace, I think we can require the latest version of any of the major browsers.

**Comment by TyIsI** [comment]
Do we set this as a bug or close this?

**Comment by mikepkes** [comment]
I think on slack the expectation was upgrade or use another browser.  Close away.

**Comment by JarrettR** [comment]
Unless we get more people working on the front end, maintaining perfect compatibility with old browsers will have to take a back seat
