### ISSUE TITLE
Power lockout, device registery

### ISSUE THREAD

**Issue by laftho** [vhs/nomos#229]
https://docs.google.com/document/d/1_rOXk8pQePBsPcn-7ukuEgTDaHpMKDf03aGdUjn4P3Q/edit

**Comment by TyIsI** [comment]
Do we still want to integrate this or do we want to set this up as external functionality that authenticates to Nomos?

**Comment by TyIsI** [comment]
A separate tool has been created for this issue. This tool uses user privileges to allow access.
