### ISSUE TITLE
Unable to Link GitHub Account

### ISSUE THREAD

**Issue by paulreimer** [vhs/nomos#253]
I was able to link my Slack + Google accounts with no issues, however, I get a redirect loop when I try to link a GitHub account.

The initial redirect disappears quickly from the URL bar, but I copied it one time:
https://github.com/login/oauth/authorize?client_id=d15d81ed8825f9e5edd1&redirect_uri=https%3A%2F%2Fmembership.vanhack.ca%2Foauth%2Fgithub.php%3Faction%3Dlink&state=2ba236fad056fd7eb8b753853b528ac7&scope=&response_type=code&approval_prompt=auto

Sometimes a browser error page is displayed (too many redirects..), eventually this GitHub error page is displayed:
```
Whoa there!
You have triggered an abuse detection mechanism.
Please wait a few minutes before you try again.
```

Google Chrome macOS, Safari iOS

**Comment by TyIsI** [comment]
Fixed after changing the GitHub app `callback` url to `https`.
