### ISSUE TITLE
Add better pagination controls

### ISSUE THREAD

**Issue by martinhansdk** [vhs/nomos#262]
Several pages in nomos have a very inconvenient way of controlling which page of data to display. We need better controls to pick the currently displayed page.

- [ ] user/grants/grants.html 
- [ ] user/webhooks/webhooks.html
- [ ] user/transactions/transactions.html
- [ ] user/accesslogs/accesslogs.html
- [ ] admin/email/email.html
- [X] admin/users/users.html
- [ ] admin/webhooks/webhooks.html
- [ ] admin/oauth/clients.html
- [ ] admin/events/events.html
- [X] admin/accesslogs/accesslogs.html
- [ ] admin/payments/payments.html
- [x] admin/ipn/records.html

**Comment by TyIsI** [comment]
Closed via PR #263
