### ISSUE TITLE
Notification hooks when membership changes take place

### ISSUE THREAD

**Issue by garthomite** [vhs/nomos#3]
In the event a membership action takes place it would be nice if dependant services can be notified of the change via HTTP post.

Inside the post would be a basic payload:

```
{
    "user": "<username/login name>",
    "memberType": "<type of member>", 
    "memberStatus": "<active, inactive>",
    "authKey": "<some auth key>
}
```

This would get posted to every pre-configured url end point. To keep it simple we could keep the auth key as a common string that only the sender/receiver know about. 

Ideally these notifications should get queued and automatically retried in the event of a failure, up to X times.

**Comment by laftho** [comment]
Web Hooks implementation https://github.com/vhs/nomos/pull/182 it's still WIP, missing some more granular permission checking and some UI work for registering webhooks but the foundation is there. RabbitMQ was deployed in a previous release: https://github.com/vhs/nomos/pull/180

I'll close this issue once the work in PR 182 is finished.

**Comment by TyIsI** [comment]
PR #182 was merged
