### ISSUE TITLE
IPN to handle different pay levels

### ISSUE THREAD

**Issue by JarrettR** [vhs/nomos#36]
Read: write in logic for new system and test that it works with the grandfather clause

**Comment by laftho** [comment]
The subscription and IPN component has been fundamentally refactored over the last 6mo but the essence of this issue - not doing it by pay level - has been resolved as how @garthomite mentioned in https://github.com/vhs/nomos/issues/36#issuecomment-86789238

See https://github.com/vhs/nomos/pull/163
