### ISSUE TITLE
Stop automatically allowing signups

### ISSUE THREAD

**Issue by JarrettR** [vhs/nomos#52]
Change the IPN to not automatically set new accounts as "active" and then email them with directions, leading them to a "signup" page that will fill out some more MMP profile info and activate their account.

As per bylaws:
 2.2: A person may apply to the directors for membership in the society and on acceptance by the directors is a member.

This additional signup page should request some more information needed for liability (address, contact info, emergency contact, etc), and then kick the account to the admin page for review.

**Comment by laftho** [comment]
This has been resolved in https://github.com/vhs/nomos/pull/163
