### ISSUE TITLE
Privilege for granting privileges

### ISSUE THREAD

**Issue by garthomite** [vhs/nomos#79]
AFAIK You need to be an admin to grant privileges but it would be nice to be give people the ability to grant out specific privileges.

For example it would be nice to be able to delegate who can grant access to the laser or mill without having to give them fill admin access.

**Comment by laftho** [comment]
feature has been added in #160.

Admin is required to create privileges that allow granting of privileges.

ie. 

- privilege of laser, code "laser"
- privilege to grant laser privilege, code "grant:laser"
- privilege to grant the privilege to grant laser privilege, code "grant:grant:laser"

I will add these to the VHS production instance once it's deployed.

Resolved.
