### ISSUE TITLE
Unexpected characters in IPN name field prevent account creation

### ISSUE THREAD

**Issue by JarrettR** [vhs/nomos#86]
Payments from Paypal accounts with an apostrophe (') in the name (eg Gibb's Maille) don't get created automagically

**Comment by laftho** [comment]
This needs to be retested with the new changes in PR #114

**Comment by JarrettR** [comment]
Accounts now get created when there is a special character, some fields just get cut off. This may have changed even more recently, so will reopen when another case study crops up
